permalink:  /posts/:title/
markdown: kramdown
extensions: [fenced_code_blocks]
plugins:
    - jekyll-seo-tag
    - jekyll-feed
author: Aaron Franks
twitter:
    username: eh_eff
title: Aaron Franks
description: Area man rambles about programming
feed:
    path: atom.xml
exclude: [node_modules]
