# Netlify config
# See https://www.netlify.com/docs/netlify-toml-reference/
[build]
  publish = "_site/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
